In [1]:
import pandas as pd

In [3]:
convergence =  pd.read_csv('convergence.csv')
# inference = pd.read_csv('inference.csv')
training_efficiency = pd.read_csv('training_efficiency.csv')
# emissions = pd.read_csv('emissions.csv')

In [4]:
convergence

,Convergence Epoch,Total Training Time (hours),Total Training Time (second),Average Epoch Time(s),Average RAM (GB),Average GPU Memory (GB),Energy Consumed (kWh),CO2 Emissions (kg)
0,1,0.545805,1964.898736,1964.898736,1.319294,0.371512,NaN,NaN

In [5]:
training_efficiency

,Total Training Time (hours),Total Training Time (second),Average Epoch Time(s),Average RAM (GB),Average GPU Memory (GB),Energy Consumed (kWh),CO2 Emissions (kg)
0,0.545805,1964.898736,1964.898736,1.319294,0.371512,NaN,0.05105